#!/usr/bin/env bun
/**
 * make_adw — generate a new one-shot ADW script from agents in the config.
 *
 * Usage:
 *   bun run <skill>/scripts/make_adw.ts --name review_docs --agents scout,builder
 *
 * Each named agent becomes one agent phase, chained by envelope. Starter agents
 * map to their concrete output types; unknown agents get GenericOutput (define a
 * concrete type in adw_modules/data_types.ts and swap it in).
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const OUTPUT_TYPES: Record<string, string> = {
  planner: "PlanOutput",
  builder: "BuildOutput",
  scout: "ScoutOutput",
  reviewer: "ReviewOutput",
  documenter: "DocumentOutput",
};

function titleCase(name: string): string {
  return name.split("_").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

function header(opts: { title: string; name: string; chain: string; imports: string; agentsList: string; phases: string }): string {
  return `#!/usr/bin/env bun
/**
 * ADW ${opts.title} — generated by make_adw.
 *
 * Usage:
 *   bun run adws/adw_${opts.name}.ts "<prompt or path/to/prompt.md>" [--config adws/adw_sf_config/sf.config.yaml] [--adw-id a1b2c3d4]
 *
 * Phases: engineer(request) -> ${opts.chain}
 */

import * as agents from "./adw_modules/agents.ts";
import * as gates from "./adw_modules/gates.ts";
import * as session from "./adw_modules/session.ts";
import { ${opts.imports}, makeAgentCall, makePhaseParams, type EnvelopeBase } from "./adw_modules/data_types.ts";
import { parseCli, resolvePrompt, runMain } from "./adw_modules/utils.ts";

const REQUIRED_AGENTS = ${opts.agentsList};

async function main(prompt: string, config: string = "adws/adw_sf_config/sf.config.yaml", adwId: string | null = null): Promise<number> {
  const cfg = agents.loadConfig(config);
  agents.validate(cfg, REQUIRED_AGENTS);
  const run = session.ensure(cfg, adwId);

  await run.phase(makePhaseParams({ name: "request", kind: "engineer", owner: run.engineer, description: "Capture the incoming ask" }), async (ph) => {
    ph.log({ input: prompt });
  });

  let previous: EnvelopeBase | null = null;
${opts.phases}
  return run.finish();
}

if (import.meta.main) {
  const { positionals, options } = parseCli(process.argv.slice(2), ["config", "adw-id"]);
  if (positionals.length < 1) {
    console.error("usage: adw_${opts.name}.ts <prompt or path/to/prompt.md> [--config <path>] [--adw-id <id>]");
    process.exit(1);
  }
  runMain(() => main(resolvePrompt(positionals[0]), options["config"] ?? "adws/adw_sf_config/sf.config.yaml", options["adw-id"] ?? null));
}
`;
}

function phaseBlock(name: string, agent: string, outputType: string): string {
  return `  // TODO: replace this description — say what THIS phase does and why.
  previous = await run.phase(
    makePhaseParams({ name: "${name}", kind: "agent", owner: "${agent}", description: "Run ${agent} over the request and hand its envelope on" }),
    (ph) => ph.call(makeAgentCall({ output_type: ${outputType}, prompt, previous, gates: [gates.artifactsExist] })),
  );
`;
}

function main(): number {
  const argv = process.argv.slice(2);
  const force = argv.includes("--force");
  const nameIdx = argv.indexOf("--name");
  const agentsIdx = argv.indexOf("--agents");
  const name = nameIdx !== -1 ? argv[nameIdx + 1] : undefined;
  const agentsArg = agentsIdx !== -1 ? argv[agentsIdx + 1] : undefined;
  if (!name || !agentsArg) {
    console.error("usage: make_adw.ts --name <snake_case_adw_name> --agents <comma,separated,agents> [--force]");
    return 1;
  }

  const agentNames = agentsArg.split(",").map((a) => a.trim()).filter(Boolean);
  if (agentNames.length === 0) {
    console.log("no agents given");
    return 1;
  }

  const types = agentNames.map((a) => OUTPUT_TYPES[a] ?? "GenericOutput");
  const seen = new Map<string, number>();
  const phases: string[] = [];
  for (let i = 0; i < agentNames.length; i++) {
    const agent = agentNames[i];
    const outputType = types[i];
    const count = (seen.get(agent) ?? 0) + 1;
    seen.set(agent, count);
    const phaseName = count === 1 ? agent : `${agent}_${count}`;
    phases.push(phaseBlock(phaseName, agent, outputType));
  }

  const uniqueTypes = [...new Set(types)].sort();
  const uniqueAgents = [...new Set(agentNames)].sort();
  const body = header({
    title: titleCase(name),
    name,
    chain: agentNames.join(" -> "),
    imports: uniqueTypes.join(", "),
    agentsList: JSON.stringify(uniqueAgents),
    phases: phases.join("\n"),
  });

  const dest = path.join(process.cwd(), "adws", `adw_${name}.ts`);
  if (existsSync(dest) && !force) {
    console.log(`${dest} already exists — use --force to overwrite`);
    return 1;
  }
  mkdirSync(path.dirname(dest), { recursive: true });
  writeFileSync(dest, body);
  console.log(`wrote ${dest}`);
  console.log("next: replace each phase description — a generated one says nothing, and the description is the only intent the trace ever shows");
  console.log(`run: bun run adws/adw_${name}.ts "your request"`);
  return 0;
}

if (import.meta.main) {
  process.exit(main());
}
