/**
 * GitHub REST implementation of `IssueProvider`, `CodeHostProvider`, AND
 * `IssueAuthoringProvider` — one class, since GitHub natively is an issue
 * tracker, a code host, and (via sub-issues) an issue-hierarchy API all at
 * once — via Node 22's native `fetch()`: deliberately not `octokit`, whose
 * full meta-package resolves to ~82MB of installed dependencies (`@octokit/app`,
 * `oauth-app`, `webhooks`, ...) for what `spf watch` actually needs, which is
 * a couple dozen REST calls, none of them exotic. `spf`'s own package stays
 * dependency-free either way.
 *
 * Auth is a classic PAT via `GITHUB_TOKEN` (`repo` scope), read once at
 * construction — matching the reference implementation's pattern and this
 * project's existing env-var-for-credentials philosophy. No pagination
 * beyond one page of 100: fine for the label-scoped queries a lean v1
 * makes (a repo with >100 open `<prefix>:ready` issues at once is not this
 * version's problem to solve).
 */
import type {
  CodeHostProvider,
  EnsureLabelsResult,
  Issue,
  IssueAuthoringProvider,
  IssueComment,
  IssueProvider,
  PrRef,
  PrStatus,
  WatchMarker,
  WatchState,
} from "./provider.ts";

const API = "https://api.github.com";
const STATES: WatchState[] = [
  "ready",
  "working",
  "review",
  "done",
  "blocked",
  "spec-ready",
  "refining",
  "refined",
  "needs-feedback",
  "continue-refinement",
];
const MARKER_RE = /<!--\s*spf-watch:\s*(\{.*?\})\s*-->/s;

/** The refine lane's leaf/container taxonomy — see `data_types.ts`'s `RefinedIssueSchema.kind`. Not a `WatchState`: these never appear on the left of a `transition()` call, so `transition()` never strips them. */
export const ISSUE_KINDS = ["epic", "feature", "story", "bug", "task"] as const;
export type IssueKind = (typeof ISSUE_KINDS)[number];

// GitHub label colors are 6 hex digits, no leading '#'.
const LABEL_META: Record<WatchState, { color: string; description: string }> = {
  ready: { color: "0e8a16", description: "spf watch will claim this issue on its next poll" },
  working: { color: "fbca04", description: "spf watch has claimed this issue and is running a chain against it" },
  review: { color: "1d76db", description: "spf watch opened a PR for this issue — awaiting merge" },
  done: { color: "5319e7", description: "spf watch's PR for this issue merged" },
  blocked: { color: "d93f0b", description: "spf watch gave up — needs a human" },
  "spec-ready": { color: "0e8a16", description: "spf watch's refine lane will claim this spec on its next poll" },
  refining: { color: "fbca04", description: "spf watch has claimed this spec and is decomposing it into issues" },
  refined: { color: "c2e0c6", description: "generated by spf watch's refine lane — promote to spf:ready when it's worth building" },
  "needs-feedback": { color: "d93f0b", description: "spf's refiner needs a human answer before it can finish decomposing this spec" },
  "continue-refinement": { color: "0e8a16", description: "add this once you've answered — spf will resume refining from where it left off" },
};

const TYPE_LABEL_META: Record<IssueKind, { color: string; description: string }> = {
  epic: { color: "5319e7", description: "a container generated by spf watch's refine lane — not directly workable" },
  feature: { color: "1d76db", description: "a container generated by spf watch's refine lane — not directly workable" },
  story: { color: "bfd4f2", description: "a leaf generated by spf watch's refine lane — vertical-slice, independently workable" },
  bug: { color: "e99695", description: "a leaf generated by spf watch's refine lane — vertical-slice, independently workable" },
  task: { color: "d4c5f9", description: "a leaf generated by spf watch's refine lane — vertical-slice, independently workable" },
};

interface GhIssue {
  id: number; // the database id — distinct from `number`, see Issue.internal_id's doc comment
  number: number;
  title: string;
  body: string | null;
  labels: Array<{ name: string } | string>;
  pull_request?: unknown;
}

export class GitHubProvider implements IssueProvider, CodeHostProvider, IssueAuthoringProvider {
  constructor(
    private readonly repo: string, // "owner/name"
    private readonly labelPrefix: string,
    private readonly token: string,
  ) {}

  private async gh<T>(path: string, init?: RequestInit): Promise<T> {
    const response = await fetch(`${API}${path}`, {
      ...init,
      headers: {
        Authorization: `Bearer ${this.token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        ...(init?.body ? { "Content-Type": "application/json" } : {}),
        ...init?.headers,
      },
    });
    if (!response.ok) {
      const detail = await response.text().catch(() => "");
      throw new Error(`GitHub ${init?.method ?? "GET"} ${path} -> ${response.status}: ${detail.slice(0, 500)}`);
    }
    if (response.status === 204) return undefined as T;
    return (await response.json()) as T;
  }

  private label(state: WatchState): string {
    return `${this.labelPrefix}:${state}`;
  }

  private typeLabel(kind: IssueKind): string {
    return `${this.labelPrefix}:type:${kind}`;
  }

  /** `null` on a real 404 (label doesn't exist yet) — any other non-2xx still throws, same as `gh()`. */
  private async getLabel(name: string): Promise<{ color: string; description: string | null } | null> {
    const response = await fetch(`${API}/repos/${this.repo}/labels/${encodeURIComponent(name)}`, {
      headers: { Authorization: `Bearer ${this.token}`, Accept: "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28" },
    });
    if (response.status === 404) return null;
    if (!response.ok) {
      const detail = await response.text().catch(() => "");
      throw new Error(`GitHub GET /repos/${this.repo}/labels/${name} -> ${response.status}: ${detail.slice(0, 500)}`);
    }
    return (await response.json()) as { color: string; description: string | null };
  }

  /**
   * Idempotent by inspection, not by "create and catch a 422": GET the
   * label first, then create/update/leave alone depending on what's
   * actually there. One fewer request in the common "already correct"
   * case, and no brittle matching against GitHub's error-message text.
   * Shared by `ensureLabels()`'s state-label and type-label passes.
   */
  private async ensureOneLabel(name: string, color: string, description: string, result: EnsureLabelsResult): Promise<void> {
    const existing = await this.getLabel(name);
    if (!existing) {
      await this.gh(`/repos/${this.repo}/labels`, { method: "POST", body: JSON.stringify({ name, color, description }) });
      result.created.push(name);
    } else if (existing.color !== color || (existing.description ?? "") !== description) {
      await this.gh(`/repos/${this.repo}/labels/${encodeURIComponent(name)}`, {
        method: "PATCH",
        body: JSON.stringify({ color, description }),
      });
      result.updated.push(name);
    } else {
      result.unchanged.push(name);
    }
  }

  async ensureLabels(): Promise<EnsureLabelsResult> {
    const result: EnsureLabelsResult = { created: [], updated: [], unchanged: [] };
    for (const state of STATES) {
      const { color, description } = LABEL_META[state];
      await this.ensureOneLabel(this.label(state), color, description, result);
    }
    for (const kind of ISSUE_KINDS) {
      const { color, description } = TYPE_LABEL_META[kind];
      await this.ensureOneLabel(this.typeLabel(kind), color, description, result);
    }
    return result;
  }

  private toIssue(raw: GhIssue): Issue {
    return {
      id: String(raw.number),
      internal_id: String(raw.id),
      title: raw.title,
      body: raw.body ?? "",
      labels: raw.labels.map((l) => (typeof l === "string" ? l : l.name)),
    };
  }

  private async listByLabel(label: string, state: "open" | "all"): Promise<Issue[]> {
    const raw = await this.gh<GhIssue[]>(
      `/repos/${this.repo}/issues?labels=${encodeURIComponent(label)}&state=${state}&per_page=100`,
    );
    return raw.filter((i) => !i.pull_request).map((i) => this.toIssue(i));
  }

  async listEligible(): Promise<Issue[]> {
    return this.listByLabel(this.label("ready"), "open");
  }

  async listInState(state: WatchState, opts?: { includeAll?: boolean }): Promise<Issue[]> {
    return this.listByLabel(this.label(state), opts?.includeAll ? "all" : "open");
  }

  async claim(issue: Issue, opts?: { from?: WatchState; to?: WatchState }): Promise<boolean> {
    const from = this.label(opts?.from ?? "ready");
    const to = this.label(opts?.to ?? "working");
    await this.gh(`/repos/${this.repo}/issues/${issue.id}/labels/${encodeURIComponent(from)}`, {
      method: "DELETE",
    }).catch(() => undefined); // already gone is fine
    await this.gh(`/repos/${this.repo}/issues/${issue.id}/labels`, {
      method: "POST",
      body: JSON.stringify({ labels: [to] }),
    });
    const fresh = await this.gh<GhIssue>(`/repos/${this.repo}/issues/${issue.id}`);
    const labels = this.toIssue(fresh).labels;
    const claimed = labels.includes(to) && !labels.includes(from);
    if (!claimed) {
      // Lost the race (or something else relabeled it) — put the source label back so it's not stuck.
      await this.gh(`/repos/${this.repo}/issues/${issue.id}/labels`, {
        method: "POST",
        body: JSON.stringify({ labels: [from] }),
      }).catch(() => undefined);
    }
    return claimed;
  }

  async transition(issue: Issue, to: WatchState, detail?: string): Promise<void> {
    for (const state of STATES) {
      const label = this.label(state);
      if (issue.labels.includes(label)) {
        await this.gh(`/repos/${this.repo}/issues/${issue.id}/labels/${encodeURIComponent(label)}`, { method: "DELETE" }).catch(
          () => undefined,
        );
      }
    }
    await this.gh(`/repos/${this.repo}/issues/${issue.id}/labels`, {
      method: "POST",
      body: JSON.stringify({ labels: [this.label(to)] }),
    });
    if (detail) await this.comment(issue, detail);
  }

  async comment(issue: Issue, body: string): Promise<void> {
    await this.gh(`/repos/${this.repo}/issues/${issue.id}/comments`, {
      method: "POST",
      body: JSON.stringify({ body }),
    });
  }

  async openPr(opts: { branch: string; title: string; body: string; base: string }): Promise<PrRef> {
    const pr = await this.gh<{ number: number; html_url: string }>(`/repos/${this.repo}/pulls`, {
      method: "POST",
      body: JSON.stringify({ title: opts.title, body: opts.body, head: opts.branch, base: opts.base }),
    });
    return { number: pr.number, branch: opts.branch, url: pr.html_url };
  }

  async prStatus(pr: PrRef): Promise<PrStatus> {
    const detail = await this.gh<{ merged: boolean; state: "open" | "closed"; head: { sha: string } }>(
      `/repos/${this.repo}/pulls/${pr.number}`,
    );
    let ciStatus: PrStatus["ciStatus"] = "pending";
    try {
      const checks = await this.gh<{ check_runs: Array<{ status: string; conclusion: string | null }> }>(
        `/repos/${this.repo}/commits/${detail.head.sha}/check-runs?per_page=100`,
      );
      if (checks.check_runs.length === 0) {
        ciStatus = "pending"; // no checks configured — never blocks a lean v1's own polling
      } else if (checks.check_runs.some((c) => c.status !== "completed")) {
        ciStatus = "pending";
      } else if (checks.check_runs.some((c) => ["failure", "timed_out", "cancelled", "action_required"].includes(c.conclusion ?? ""))) {
        ciStatus = "failure";
      } else {
        ciStatus = "success";
      }
    } catch {
      ciStatus = "pending"; // check-runs lookup failing shouldn't block merge/close detection
    }
    return { merged: detail.merged, state: detail.state, ciStatus };
  }

  /** `IssueAuthoringProvider` — the refine lane's own need (see `provider.ts`'s module doc). */
  async createIssue(input: { title: string; body: string; labels: string[] }): Promise<Issue> {
    const raw = await this.gh<GhIssue>(`/repos/${this.repo}/issues`, {
      method: "POST",
      body: JSON.stringify({ title: input.title, body: input.body, labels: input.labels }),
    });
    return this.toIssue(raw);
  }

  /**
   * `POST /repos/{o}/{r}/issues/{parent_number}/sub_issues` — GitHub's
   * native sub-issue link. Confirmed against GitHub's own REST docs: the
   * body param is `sub_issue_id`, the CHILD's database id, not its issue
   * number — hence `linkChild` requiring `child.internal_id` rather than
   * `child.id`. GitHub's documented limits (not enforced client-side here):
   * 100 sub-issues per parent, 8 levels of nesting.
   */
  async linkChild(parent: Issue, child: Issue): Promise<void> {
    if (!child.internal_id) {
      throw new Error(`linkChild: child issue #${child.id} has no internal_id — only an issue this provider just created/fetched can be linked`);
    }
    await this.gh(`/repos/${this.repo}/issues/${parent.id}/sub_issues`, {
      method: "POST",
      body: JSON.stringify({ sub_issue_id: Number(child.internal_id) }),
    });
  }

  /** The single fetch every comment-reading method (`findMarkerComment`, `listComments`) builds on. */
  private async fetchComments(issueId: string): Promise<Array<{ id: number; body: string; user: { login: string } | null; created_at: string }>> {
    return this.gh(`/repos/${this.repo}/issues/${issueId}/comments?per_page=100`);
  }

  private async findMarkerComment(issueId: string): Promise<{ id: number; marker: WatchMarker } | null> {
    const comments = await this.fetchComments(issueId);
    let found: { id: number; marker: WatchMarker } | null = null;
    for (const c of comments) {
      const match = MARKER_RE.exec(c.body || "");
      if (!match) continue;
      try {
        found = { id: c.id, marker: JSON.parse(match[1]) };
      } catch {
        // malformed marker JSON — tolerate it and keep looking, like the reference implementation does
      }
    }
    return found;
  }

  async readMarker(issue: Issue): Promise<WatchMarker | null> {
    const found = await this.findMarkerComment(issue.id);
    return found?.marker ?? null;
  }

  async writeMarker(issue: Issue, marker: WatchMarker): Promise<void> {
    const body = `<!-- spf-watch: ${JSON.stringify(marker)} -->`;
    const existing = await this.findMarkerComment(issue.id);
    if (existing) {
      await this.gh(`/repos/${this.repo}/issues/comments/${existing.id}`, { method: "PATCH", body: JSON.stringify({ body }) });
    } else {
      await this.gh(`/repos/${this.repo}/issues/${issue.id}/comments`, { method: "POST", body: JSON.stringify({ body }) });
    }
  }

  /** Oldest-first (GitHub's own comment order), the hidden marker comment filtered out. */
  async listComments(issue: Issue): Promise<IssueComment[]> {
    const comments = await this.fetchComments(issue.id);
    return comments
      .filter((c) => !MARKER_RE.test(c.body || ""))
      .map((c) => ({ id: String(c.id), author: c.user?.login ?? "unknown", created_at: c.created_at, body: c.body || "" }));
  }

  /** `state_reason: "completed"` — the refine lane's own reason for closing a spec once it's fully decomposed; see `finishSpec` in `watch.ts`. */
  async closeIssue(issue: Issue): Promise<void> {
    await this.gh(`/repos/${this.repo}/issues/${issue.id}`, {
      method: "PATCH",
      body: JSON.stringify({ state: "closed", state_reason: "completed" }),
    });
  }
}
